# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T09:43:15+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, ConfigDict, Field, RootModel, SecretStr, conint, constr


class AccessEndpointType(Enum):
    STREAMING = 'STREAMING'


class AccountName(RootModel[SecretStr]):
    root: SecretStr


class AccountPassword(RootModel[SecretStr]):
    root: SecretStr


class Action(Enum):
    CLIPBOARD_COPY_FROM_LOCAL_DEVICE = 'CLIPBOARD_COPY_FROM_LOCAL_DEVICE'
    CLIPBOARD_COPY_TO_LOCAL_DEVICE = 'CLIPBOARD_COPY_TO_LOCAL_DEVICE'
    FILE_UPLOAD = 'FILE_UPLOAD'
    FILE_DOWNLOAD = 'FILE_DOWNLOAD'
    PRINTING_TO_LOCAL_DEVICE = 'PRINTING_TO_LOCAL_DEVICE'
    DOMAIN_PASSWORD_SIGNIN = 'DOMAIN_PASSWORD_SIGNIN'
    DOMAIN_SMART_CARD_SIGNIN = 'DOMAIN_SMART_CARD_SIGNIN'


class AppVisibility(Enum):
    ALL = 'ALL'
    ASSOCIATED = 'ASSOCIATED'


class ApplicationAttribute(Enum):
    LAUNCH_PARAMETERS = 'LAUNCH_PARAMETERS'
    WORKING_DIRECTORY = 'WORKING_DIRECTORY'


class ApplicationAttributes(RootModel[List[ApplicationAttribute]]):
    root: List[ApplicationAttribute] = Field(..., max_length=2)


class AppstreamAgentVersion(RootModel[constr(min_length=1, max_length=100)]):
    root: constr(min_length=1, max_length=100)


class Arn(
    RootModel[
        constr(
            pattern=r'^arn:aws(?:\-cn|\-iso\-b|\-iso|\-us\-gov)?:[A-Za-z0-9][A-Za-z0-9_/.-]{0,62}:[A-Za-z0-9_/.-]{0,63}:[A-Za-z0-9_/.-]{0,63}:[A-Za-z0-9][A-Za-z0-9:_/+=,@.\\-]{0,1023}$'
        )
    ]
):
    root: constr(
        pattern=r'^arn:aws(?:\-cn|\-iso\-b|\-iso|\-us\-gov)?:[A-Za-z0-9][A-Za-z0-9_/.-]{0,62}:[A-Za-z0-9_/.-]{0,63}:[A-Za-z0-9_/.-]{0,63}:[A-Za-z0-9][A-Za-z0-9:_/+=,@.\\-]{0,1023}$'
    )


class ArnList(RootModel[List[Arn]]):
    root: List[Arn]


class AssociateApplicationToEntitlementResult(BaseModel):
    pass


class AssociateFleetResult(BaseModel):
    pass


class AuthenticationType(Enum):
    API = 'API'
    SAML = 'SAML'
    USERPOOL = 'USERPOOL'
    AWS_AD = 'AWS_AD'


class AwsAccountId(RootModel[constr(pattern=r'^\d+$')]):
    root: constr(pattern=r'^\d+$')


class AwsAccountIdList(RootModel[List[AwsAccountId]]):
    root: List[AwsAccountId] = Field(..., max_length=5, min_length=1)


class Boolean(RootModel[bool]):
    root: bool


class BooleanObject(RootModel[bool]):
    root: bool


class CertificateBasedAuthStatus(Enum):
    DISABLED = 'DISABLED'
    ENABLED = 'ENABLED'
    ENABLED_NO_DIRECTORY_LOGIN_FALLBACK = 'ENABLED_NO_DIRECTORY_LOGIN_FALLBACK'


class ConcurrentModificationException(RootModel[Any]):
    root: Any


class CreateUsageReportSubscriptionRequest(BaseModel):
    pass


class CreateUserResult(BaseModel):
    pass


class DeleteAppBlockResult(BaseModel):
    pass


class DeleteApplicationResult(BaseModel):
    pass


class DeleteDirectoryConfigResult(BaseModel):
    pass


class DeleteEntitlementResult(BaseModel):
    pass


class DeleteFleetResult(BaseModel):
    pass


class DeleteImagePermissionsResult(BaseModel):
    pass


class DeleteStackResult(BaseModel):
    pass


class DeleteUsageReportSubscriptionRequest(BaseModel):
    pass


class DeleteUsageReportSubscriptionResult(BaseModel):
    pass


class DeleteUserResult(BaseModel):
    pass


class DescribeImagesMaxResults(RootModel[conint(ge=0, le=25)]):
    root: conint(ge=0, le=25)


class Description(RootModel[constr(max_length=256)]):
    root: constr(max_length=256)


class DirectoryName(RootModel[str]):
    root: str


class DirectoryNameList(RootModel[List[DirectoryName]]):
    root: List[DirectoryName]


class DisableUserResult(BaseModel):
    pass


class DisassociateApplicationFleetResult(BaseModel):
    pass


class DisassociateApplicationFromEntitlementResult(BaseModel):
    pass


class DisassociateFleetResult(BaseModel):
    pass


class DisplayName(RootModel[constr(max_length=100)]):
    root: constr(max_length=100)


class Domain(RootModel[constr(min_length=1, max_length=64)]):
    root: constr(min_length=1, max_length=64) = Field(
        ..., description='GSuite domain for GDrive integration.'
    )


class DomainList(RootModel[List[Domain]]):
    root: List[Domain] = Field(..., max_length=50)


class EmbedHostDomain(
    RootModel[
        constr(
            pattern=r'(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z0-9][a-z0-9-]{0,61}[a-z0-9]',
            max_length=128,
        )
    ]
):
    root: constr(
        pattern=r'(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z0-9][a-z0-9-]{0,61}[a-z0-9]',
        max_length=128,
    ) = Field(
        ...,
        description='Specifies a valid domain that can embed AppStream. Valid examples include: ["testorigin.tt--com", "testingorigin.com.us", "test.com.us"] Invalid examples include: ["test,com", ".com", "h*llo.com". ""]',
    )


class EmbedHostDomains(RootModel[List[EmbedHostDomain]]):
    root: List[EmbedHostDomain] = Field(..., max_length=20, min_length=1)


class EnableUserResult(BaseModel):
    pass


class EntitlementAlreadyExistsException(RootModel[Any]):
    root: Any


class EntitlementNotFoundException(RootModel[Any]):
    root: Any


class ExpireSessionResult(BaseModel):
    pass


class FeedbackURL(RootModel[constr(max_length=1000)]):
    root: constr(max_length=1000)


class FleetAttribute(Enum):
    VPC_CONFIGURATION = 'VPC_CONFIGURATION'
    VPC_CONFIGURATION_SECURITY_GROUP_IDS = 'VPC_CONFIGURATION_SECURITY_GROUP_IDS'
    DOMAIN_JOIN_INFO = 'DOMAIN_JOIN_INFO'
    IAM_ROLE_ARN = 'IAM_ROLE_ARN'
    USB_DEVICE_FILTER_STRINGS = 'USB_DEVICE_FILTER_STRINGS'
    SESSION_SCRIPT_S3_LOCATION = 'SESSION_SCRIPT_S3_LOCATION'


class FleetAttributes(RootModel[List[FleetAttribute]]):
    root: List[FleetAttribute] = Field(..., description='The fleet attributes.')


class FleetErrorCode(Enum):
    IAM_SERVICE_ROLE_MISSING_ENI_DESCRIBE_ACTION = (
        'IAM_SERVICE_ROLE_MISSING_ENI_DESCRIBE_ACTION'
    )
    IAM_SERVICE_ROLE_MISSING_ENI_CREATE_ACTION = (
        'IAM_SERVICE_ROLE_MISSING_ENI_CREATE_ACTION'
    )
    IAM_SERVICE_ROLE_MISSING_ENI_DELETE_ACTION = (
        'IAM_SERVICE_ROLE_MISSING_ENI_DELETE_ACTION'
    )
    NETWORK_INTERFACE_LIMIT_EXCEEDED = 'NETWORK_INTERFACE_LIMIT_EXCEEDED'
    INTERNAL_SERVICE_ERROR = 'INTERNAL_SERVICE_ERROR'
    IAM_SERVICE_ROLE_IS_MISSING = 'IAM_SERVICE_ROLE_IS_MISSING'
    MACHINE_ROLE_IS_MISSING = 'MACHINE_ROLE_IS_MISSING'
    STS_DISABLED_IN_REGION = 'STS_DISABLED_IN_REGION'
    SUBNET_HAS_INSUFFICIENT_IP_ADDRESSES = 'SUBNET_HAS_INSUFFICIENT_IP_ADDRESSES'
    IAM_SERVICE_ROLE_MISSING_DESCRIBE_SUBNET_ACTION = (
        'IAM_SERVICE_ROLE_MISSING_DESCRIBE_SUBNET_ACTION'
    )
    SUBNET_NOT_FOUND = 'SUBNET_NOT_FOUND'
    IMAGE_NOT_FOUND = 'IMAGE_NOT_FOUND'
    INVALID_SUBNET_CONFIGURATION = 'INVALID_SUBNET_CONFIGURATION'
    SECURITY_GROUPS_NOT_FOUND = 'SECURITY_GROUPS_NOT_FOUND'
    IGW_NOT_ATTACHED = 'IGW_NOT_ATTACHED'
    IAM_SERVICE_ROLE_MISSING_DESCRIBE_SECURITY_GROUPS_ACTION = (
        'IAM_SERVICE_ROLE_MISSING_DESCRIBE_SECURITY_GROUPS_ACTION'
    )
    FLEET_STOPPED = 'FLEET_STOPPED'
    FLEET_INSTANCE_PROVISIONING_FAILURE = 'FLEET_INSTANCE_PROVISIONING_FAILURE'
    DOMAIN_JOIN_ERROR_FILE_NOT_FOUND = 'DOMAIN_JOIN_ERROR_FILE_NOT_FOUND'
    DOMAIN_JOIN_ERROR_ACCESS_DENIED = 'DOMAIN_JOIN_ERROR_ACCESS_DENIED'
    DOMAIN_JOIN_ERROR_LOGON_FAILURE = 'DOMAIN_JOIN_ERROR_LOGON_FAILURE'
    DOMAIN_JOIN_ERROR_INVALID_PARAMETER = 'DOMAIN_JOIN_ERROR_INVALID_PARAMETER'
    DOMAIN_JOIN_ERROR_MORE_DATA = 'DOMAIN_JOIN_ERROR_MORE_DATA'
    DOMAIN_JOIN_ERROR_NO_SUCH_DOMAIN = 'DOMAIN_JOIN_ERROR_NO_SUCH_DOMAIN'
    DOMAIN_JOIN_ERROR_NOT_SUPPORTED = 'DOMAIN_JOIN_ERROR_NOT_SUPPORTED'
    DOMAIN_JOIN_NERR_INVALID_WORKGROUP_NAME = 'DOMAIN_JOIN_NERR_INVALID_WORKGROUP_NAME'
    DOMAIN_JOIN_NERR_WORKSTATION_NOT_STARTED = (
        'DOMAIN_JOIN_NERR_WORKSTATION_NOT_STARTED'
    )
    DOMAIN_JOIN_ERROR_DS_MACHINE_ACCOUNT_QUOTA_EXCEEDED = (
        'DOMAIN_JOIN_ERROR_DS_MACHINE_ACCOUNT_QUOTA_EXCEEDED'
    )
    DOMAIN_JOIN_NERR_PASSWORD_EXPIRED = 'DOMAIN_JOIN_NERR_PASSWORD_EXPIRED'
    DOMAIN_JOIN_INTERNAL_SERVICE_ERROR = 'DOMAIN_JOIN_INTERNAL_SERVICE_ERROR'


class FleetState(Enum):
    STARTING = 'STARTING'
    RUNNING = 'RUNNING'
    STOPPING = 'STOPPING'
    STOPPED = 'STOPPED'


class FleetType(Enum):
    ALWAYS_ON = 'ALWAYS_ON'
    ON_DEMAND = 'ON_DEMAND'
    ELASTIC = 'ELASTIC'


class ImageBuilderState(Enum):
    PENDING = 'PENDING'
    UPDATING_AGENT = 'UPDATING_AGENT'
    RUNNING = 'RUNNING'
    STOPPING = 'STOPPING'
    STOPPED = 'STOPPED'
    REBOOTING = 'REBOOTING'
    SNAPSHOTTING = 'SNAPSHOTTING'
    DELETING = 'DELETING'
    FAILED = 'FAILED'
    UPDATING = 'UPDATING'
    PENDING_QUALIFICATION = 'PENDING_QUALIFICATION'


class ImageBuilderStateChangeReasonCode(Enum):
    INTERNAL_ERROR = 'INTERNAL_ERROR'
    IMAGE_UNAVAILABLE = 'IMAGE_UNAVAILABLE'


class ImagePermissions(BaseModel):
    allowFleet: Optional[BooleanObject] = None
    allowImageBuilder: Optional[BooleanObject] = None


class ImageState(Enum):
    PENDING = 'PENDING'
    AVAILABLE = 'AVAILABLE'
    FAILED = 'FAILED'
    COPYING = 'COPYING'
    DELETING = 'DELETING'
    CREATING = 'CREATING'
    IMPORTING = 'IMPORTING'


class ImageStateChangeReasonCode(Enum):
    INTERNAL_ERROR = 'INTERNAL_ERROR'
    IMAGE_BUILDER_NOT_AVAILABLE = 'IMAGE_BUILDER_NOT_AVAILABLE'
    IMAGE_COPY_FAILURE = 'IMAGE_COPY_FAILURE'


class IncompatibleImageException(RootModel[Any]):
    root: Any


class Integer(RootModel[int]):
    root: int


class InvalidAccountStatusException(RootModel[Any]):
    root: Any


class InvalidParameterCombinationException(RootModel[Any]):
    root: Any


class InvalidRoleException(RootModel[Any]):
    root: Any


class LimitExceededException(RootModel[Any]):
    root: Any


class ListTagsForResourceRequest(BaseModel):
    ResourceArn: Arn


class Long(RootModel[int]):
    root: int


class MaxResults(RootModel[conint(ge=0, le=500)]):
    root: conint(ge=0, le=500)


class MessageAction(Enum):
    SUPPRESS = 'SUPPRESS'
    RESEND = 'RESEND'


class Name(RootModel[constr(pattern=r'^[a-zA-Z0-9][a-zA-Z0-9_.-]{0,100}$')]):
    root: constr(pattern=r'^[a-zA-Z0-9][a-zA-Z0-9_.-]{0,100}$')


class OperationNotPermittedException(RootModel[Any]):
    root: Any


class OrganizationalUnitDistinguishedName(RootModel[constr(max_length=2000)]):
    root: constr(max_length=2000)


class OrganizationalUnitDistinguishedNamesList(
    RootModel[List[OrganizationalUnitDistinguishedName]]
):
    root: List[OrganizationalUnitDistinguishedName]


class Permission(Enum):
    ENABLED = 'ENABLED'
    DISABLED = 'DISABLED'


class PlatformType(Enum):
    WINDOWS = 'WINDOWS'
    WINDOWS_SERVER_2016 = 'WINDOWS_SERVER_2016'
    WINDOWS_SERVER_2019 = 'WINDOWS_SERVER_2019'
    AMAZON_LINUX2 = 'AMAZON_LINUX2'


class Platforms(RootModel[List[PlatformType]]):
    root: List[PlatformType] = Field(..., max_length=4)


class PreferredProtocol(Enum):
    TCP = 'TCP'
    UDP = 'UDP'


class RedirectURL(RootModel[constr(max_length=1000)]):
    root: constr(max_length=1000)


class RegionName(RootModel[constr(min_length=1, max_length=32)]):
    root: constr(min_length=1, max_length=32)


class RequestLimitExceededException(RootModel[Any]):
    root: Any


class ResourceAlreadyExistsException(RootModel[Any]):
    root: Any


class ResourceIdentifier(RootModel[constr(min_length=1, max_length=2048)]):
    root: constr(min_length=1, max_length=2048) = Field(
        ..., description='The ARN of the resource.'
    )


class ResourceInUseException(RootModel[Any]):
    root: Any


class ResourceNotAvailableException(RootModel[Any]):
    root: Any


class ResourceNotFoundException(RootModel[Any]):
    root: Any


class S3Bucket(
    RootModel[constr(pattern=r'^[0-9a-z\.\-]*(?<!\.)$', min_length=3, max_length=63)]
):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: constr(pattern=r'^[0-9a-z\.\-]*(?<!\.)$', min_length=3, max_length=63)


class S3Key(RootModel[constr(min_length=1, max_length=1024)]):
    root: constr(min_length=1, max_length=1024)


class S3Location(BaseModel):
    S3Bucket_1: S3Bucket = Field(..., alias='S3Bucket')
    S3Key_1: S3Key = Field(..., alias='S3Key')


class ServiceAccountCredentials(BaseModel):
    AccountName_1: AccountName = Field(..., alias='AccountName')
    AccountPassword_1: AccountPassword = Field(..., alias='AccountPassword')


class SessionConnectionState(Enum):
    CONNECTED = 'CONNECTED'
    NOT_CONNECTED = 'NOT_CONNECTED'


class SessionState(Enum):
    ACTIVE = 'ACTIVE'
    PENDING = 'PENDING'
    EXPIRED = 'EXPIRED'


class SettingsGroup(RootModel[constr(max_length=100)]):
    root: constr(max_length=100)


class SharedImagePermissions(BaseModel):
    imagePermissions: ImagePermissions
    sharedAccountId: AwsAccountId


class SharedImagePermissionsList(RootModel[List[SharedImagePermissions]]):
    root: List[SharedImagePermissions]


class StackAttribute(Enum):
    STORAGE_CONNECTORS = 'STORAGE_CONNECTORS'
    STORAGE_CONNECTOR_HOMEFOLDERS = 'STORAGE_CONNECTOR_HOMEFOLDERS'
    STORAGE_CONNECTOR_GOOGLE_DRIVE = 'STORAGE_CONNECTOR_GOOGLE_DRIVE'
    STORAGE_CONNECTOR_ONE_DRIVE = 'STORAGE_CONNECTOR_ONE_DRIVE'
    REDIRECT_URL = 'REDIRECT_URL'
    FEEDBACK_URL = 'FEEDBACK_URL'
    THEME_NAME = 'THEME_NAME'
    USER_SETTINGS = 'USER_SETTINGS'
    EMBED_HOST_DOMAINS = 'EMBED_HOST_DOMAINS'
    IAM_ROLE_ARN = 'IAM_ROLE_ARN'
    ACCESS_ENDPOINTS = 'ACCESS_ENDPOINTS'
    STREAMING_EXPERIENCE_SETTINGS = 'STREAMING_EXPERIENCE_SETTINGS'


class StackAttributes(RootModel[List[StackAttribute]]):
    root: List[StackAttribute]


class StackErrorCode(Enum):
    STORAGE_CONNECTOR_ERROR = 'STORAGE_CONNECTOR_ERROR'
    INTERNAL_SERVICE_ERROR = 'INTERNAL_SERVICE_ERROR'


class StartFleetResult(BaseModel):
    pass


class StopFleetResult(BaseModel):
    pass


class StorageConnectorType(Enum):
    HOMEFOLDERS = 'HOMEFOLDERS'
    GOOGLE_DRIVE = 'GOOGLE_DRIVE'
    ONE_DRIVE = 'ONE_DRIVE'


class StreamView(Enum):
    APP = 'APP'
    DESKTOP = 'DESKTOP'


class StreamingExperienceSettings(BaseModel):
    PreferredProtocol_1: Optional[PreferredProtocol] = Field(
        None, alias='PreferredProtocol'
    )


class StreamingUrlUserId(
    RootModel[constr(pattern=r'[\w+=,.@-]*', min_length=2, max_length=32)]
):
    root: constr(pattern=r'[\w+=,.@-]*', min_length=2, max_length=32)


class String(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class StringList(RootModel[List[String]]):
    root: List[String]


class SubnetIdList(RootModel[List[String]]):
    root: List[String] = Field(..., description='The subnet identifiers.')


class TagKey(
    RootModel[
        constr(
            pattern=r'^(^(?!aws:).[\p{L}\p{Z}\p{N}_.:/=+\-@]*)$',
            min_length=1,
            max_length=128,
        )
    ]
):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: constr(
        pattern=r'^(^(?!aws:).[\p{L}\p{Z}\p{N}_.:/=+\-@]*)$',
        min_length=1,
        max_length=128,
    )


class TagKeyList(RootModel[List[TagKey]]):
    root: List[TagKey] = Field(..., max_length=50, min_length=1)


class TagResourceResponse(BaseModel):
    pass


class TagValue(
    RootModel[
        constr(pattern=r'^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$', min_length=0, max_length=256)
    ]
):
    root: constr(
        pattern=r'^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$', min_length=0, max_length=256
    )


class Tags(RootModel[Optional[Dict[str, TagValue]]]):
    root: Optional[Dict[str, TagValue]] = None


class Timestamp(RootModel[datetime]):
    root: datetime


class UntagResourceRequest(BaseModel):
    ResourceArn: Arn
    TagKeys: TagKeyList


class UntagResourceResponse(BaseModel):
    pass


class UpdateApplicationRequest(BaseModel):
    AppBlockArn: Optional[Arn] = None
    AttributesToDelete: Optional[ApplicationAttributes] = None
    Description_1: Optional[Description] = Field(None, alias='Description')
    DisplayName_1: Optional[DisplayName] = Field(None, alias='DisplayName')
    IconS3Location: Optional[S3Location] = None
    LaunchParameters: Optional[String] = None
    LaunchPath: Optional[String] = None
    Name_1: Name = Field(..., alias='Name')
    WorkingDirectory: Optional[String] = None


class UpdateImagePermissionsRequest(BaseModel):
    ImagePermissions_1: ImagePermissions = Field(..., alias='ImagePermissions')
    Name_1: Name = Field(..., alias='Name')
    SharedAccountId: AwsAccountId


class UpdateImagePermissionsResult(BaseModel):
    pass


class UsageReportExecutionErrorCode(Enum):
    RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND'
    ACCESS_DENIED = 'ACCESS_DENIED'
    INTERNAL_SERVICE_ERROR = 'INTERNAL_SERVICE_ERROR'


class UsageReportSchedule(Enum):
    DAILY = 'DAILY'


class UsbDeviceFilterString(
    RootModel[
        constr(
            pattern=r'^((\w*)\s*(\w*)\s*\,\s*(\w*)\s*\,\s*\*?(\w*)\s*\,\s*\*?(\w*)\s*\,\s*\*?\d*\s*\,\s*\*?\d*\s*\,\s*[0-1]\s*\,\s*[0-1]\s*)$',
            min_length=0,
            max_length=100,
        )
    ]
):
    root: constr(
        pattern=r'^((\w*)\s*(\w*)\s*\,\s*(\w*)\s*\,\s*\*?(\w*)\s*\,\s*\*?(\w*)\s*\,\s*\*?\d*\s*\,\s*\*?\d*\s*\,\s*[0-1]\s*\,\s*[0-1]\s*)$',
        min_length=0,
        max_length=100,
    )


class UsbDeviceFilterStrings(RootModel[List[UsbDeviceFilterString]]):
    root: List[UsbDeviceFilterString]


class UserAttributeValue(RootModel[SecretStr]):
    root: SecretStr


class UserId(RootModel[constr(min_length=2, max_length=128)]):
    root: constr(min_length=2, max_length=128)


class UserSetting(BaseModel):
    Action_1: Action = Field(..., alias='Action')
    Permission_1: Permission = Field(..., alias='Permission')


class UserSettingList(RootModel[List[UserSetting]]):
    root: List[UserSetting] = Field(..., min_length=1)


class UserStackAssociationErrorCode(Enum):
    STACK_NOT_FOUND = 'STACK_NOT_FOUND'
    USER_NAME_NOT_FOUND = 'USER_NAME_NOT_FOUND'
    DIRECTORY_NOT_FOUND = 'DIRECTORY_NOT_FOUND'
    INTERNAL_ERROR = 'INTERNAL_ERROR'


class Username(RootModel[SecretStr]):
    root: SecretStr


class VisibilityType(Enum):
    PUBLIC = 'PUBLIC'
    PRIVATE = 'PRIVATE'
    SHARED = 'SHARED'


class XAmzTarget(Enum):
    PhotonAdminProxyService_AssociateApplicationFleet = (
        'PhotonAdminProxyService.AssociateApplicationFleet'
    )


class XAmzTarget1(Enum):
    PhotonAdminProxyService_AssociateApplicationToEntitlement = (
        'PhotonAdminProxyService.AssociateApplicationToEntitlement'
    )


class XAmzTarget2(Enum):
    PhotonAdminProxyService_AssociateFleet = 'PhotonAdminProxyService.AssociateFleet'


class XAmzTarget3(Enum):
    PhotonAdminProxyService_BatchAssociateUserStack = (
        'PhotonAdminProxyService.BatchAssociateUserStack'
    )


class XAmzTarget4(Enum):
    PhotonAdminProxyService_BatchDisassociateUserStack = (
        'PhotonAdminProxyService.BatchDisassociateUserStack'
    )


class XAmzTarget5(Enum):
    PhotonAdminProxyService_CopyImage = 'PhotonAdminProxyService.CopyImage'


class XAmzTarget6(Enum):
    PhotonAdminProxyService_CreateAppBlock = 'PhotonAdminProxyService.CreateAppBlock'


class XAmzTarget7(Enum):
    PhotonAdminProxyService_CreateApplication = (
        'PhotonAdminProxyService.CreateApplication'
    )


class XAmzTarget8(Enum):
    PhotonAdminProxyService_CreateDirectoryConfig = (
        'PhotonAdminProxyService.CreateDirectoryConfig'
    )


class XAmzTarget9(Enum):
    PhotonAdminProxyService_CreateEntitlement = (
        'PhotonAdminProxyService.CreateEntitlement'
    )


class XAmzTarget10(Enum):
    PhotonAdminProxyService_CreateFleet = 'PhotonAdminProxyService.CreateFleet'


class XAmzTarget11(Enum):
    PhotonAdminProxyService_CreateImageBuilder = (
        'PhotonAdminProxyService.CreateImageBuilder'
    )


class XAmzTarget12(Enum):
    PhotonAdminProxyService_CreateImageBuilderStreamingURL = (
        'PhotonAdminProxyService.CreateImageBuilderStreamingURL'
    )


class XAmzTarget13(Enum):
    PhotonAdminProxyService_CreateStack = 'PhotonAdminProxyService.CreateStack'


class XAmzTarget14(Enum):
    PhotonAdminProxyService_CreateStreamingURL = (
        'PhotonAdminProxyService.CreateStreamingURL'
    )


class XAmzTarget15(Enum):
    PhotonAdminProxyService_CreateUpdatedImage = (
        'PhotonAdminProxyService.CreateUpdatedImage'
    )


class XAmzTarget16(Enum):
    PhotonAdminProxyService_CreateUsageReportSubscription = (
        'PhotonAdminProxyService.CreateUsageReportSubscription'
    )


class XAmzTarget17(Enum):
    PhotonAdminProxyService_CreateUser = 'PhotonAdminProxyService.CreateUser'


class XAmzTarget18(Enum):
    PhotonAdminProxyService_DeleteAppBlock = 'PhotonAdminProxyService.DeleteAppBlock'


class XAmzTarget19(Enum):
    PhotonAdminProxyService_DeleteApplication = (
        'PhotonAdminProxyService.DeleteApplication'
    )


class XAmzTarget20(Enum):
    PhotonAdminProxyService_DeleteDirectoryConfig = (
        'PhotonAdminProxyService.DeleteDirectoryConfig'
    )


class XAmzTarget21(Enum):
    PhotonAdminProxyService_DeleteEntitlement = (
        'PhotonAdminProxyService.DeleteEntitlement'
    )


class XAmzTarget22(Enum):
    PhotonAdminProxyService_DeleteFleet = 'PhotonAdminProxyService.DeleteFleet'


class XAmzTarget23(Enum):
    PhotonAdminProxyService_DeleteImage = 'PhotonAdminProxyService.DeleteImage'


class XAmzTarget24(Enum):
    PhotonAdminProxyService_DeleteImageBuilder = (
        'PhotonAdminProxyService.DeleteImageBuilder'
    )


class XAmzTarget25(Enum):
    PhotonAdminProxyService_DeleteImagePermissions = (
        'PhotonAdminProxyService.DeleteImagePermissions'
    )


class XAmzTarget26(Enum):
    PhotonAdminProxyService_DeleteStack = 'PhotonAdminProxyService.DeleteStack'


class XAmzTarget27(Enum):
    PhotonAdminProxyService_DeleteUsageReportSubscription = (
        'PhotonAdminProxyService.DeleteUsageReportSubscription'
    )


class XAmzTarget28(Enum):
    PhotonAdminProxyService_DeleteUser = 'PhotonAdminProxyService.DeleteUser'


class XAmzTarget29(Enum):
    PhotonAdminProxyService_DescribeAppBlocks = (
        'PhotonAdminProxyService.DescribeAppBlocks'
    )


class XAmzTarget30(Enum):
    PhotonAdminProxyService_DescribeApplicationFleetAssociations = (
        'PhotonAdminProxyService.DescribeApplicationFleetAssociations'
    )


class XAmzTarget31(Enum):
    PhotonAdminProxyService_DescribeApplications = (
        'PhotonAdminProxyService.DescribeApplications'
    )


class XAmzTarget32(Enum):
    PhotonAdminProxyService_DescribeDirectoryConfigs = (
        'PhotonAdminProxyService.DescribeDirectoryConfigs'
    )


class XAmzTarget33(Enum):
    PhotonAdminProxyService_DescribeEntitlements = (
        'PhotonAdminProxyService.DescribeEntitlements'
    )


class XAmzTarget34(Enum):
    PhotonAdminProxyService_DescribeFleets = 'PhotonAdminProxyService.DescribeFleets'


class XAmzTarget35(Enum):
    PhotonAdminProxyService_DescribeImageBuilders = (
        'PhotonAdminProxyService.DescribeImageBuilders'
    )


class XAmzTarget36(Enum):
    PhotonAdminProxyService_DescribeImagePermissions = (
        'PhotonAdminProxyService.DescribeImagePermissions'
    )


class XAmzTarget37(Enum):
    PhotonAdminProxyService_DescribeImages = 'PhotonAdminProxyService.DescribeImages'


class XAmzTarget38(Enum):
    PhotonAdminProxyService_DescribeSessions = (
        'PhotonAdminProxyService.DescribeSessions'
    )


class XAmzTarget39(Enum):
    PhotonAdminProxyService_DescribeStacks = 'PhotonAdminProxyService.DescribeStacks'


class XAmzTarget40(Enum):
    PhotonAdminProxyService_DescribeUsageReportSubscriptions = (
        'PhotonAdminProxyService.DescribeUsageReportSubscriptions'
    )


class XAmzTarget41(Enum):
    PhotonAdminProxyService_DescribeUserStackAssociations = (
        'PhotonAdminProxyService.DescribeUserStackAssociations'
    )


class XAmzTarget42(Enum):
    PhotonAdminProxyService_DescribeUsers = 'PhotonAdminProxyService.DescribeUsers'


class XAmzTarget43(Enum):
    PhotonAdminProxyService_DisableUser = 'PhotonAdminProxyService.DisableUser'


class XAmzTarget44(Enum):
    PhotonAdminProxyService_DisassociateApplicationFleet = (
        'PhotonAdminProxyService.DisassociateApplicationFleet'
    )


class XAmzTarget45(Enum):
    PhotonAdminProxyService_DisassociateApplicationFromEntitlement = (
        'PhotonAdminProxyService.DisassociateApplicationFromEntitlement'
    )


class XAmzTarget46(Enum):
    PhotonAdminProxyService_DisassociateFleet = (
        'PhotonAdminProxyService.DisassociateFleet'
    )


class XAmzTarget47(Enum):
    PhotonAdminProxyService_EnableUser = 'PhotonAdminProxyService.EnableUser'


class XAmzTarget48(Enum):
    PhotonAdminProxyService_ExpireSession = 'PhotonAdminProxyService.ExpireSession'


class XAmzTarget49(Enum):
    PhotonAdminProxyService_ListAssociatedFleets = (
        'PhotonAdminProxyService.ListAssociatedFleets'
    )


class XAmzTarget50(Enum):
    PhotonAdminProxyService_ListAssociatedStacks = (
        'PhotonAdminProxyService.ListAssociatedStacks'
    )


class XAmzTarget51(Enum):
    PhotonAdminProxyService_ListEntitledApplications = (
        'PhotonAdminProxyService.ListEntitledApplications'
    )


class XAmzTarget52(Enum):
    PhotonAdminProxyService_ListTagsForResource = (
        'PhotonAdminProxyService.ListTagsForResource'
    )


class XAmzTarget53(Enum):
    PhotonAdminProxyService_StartFleet = 'PhotonAdminProxyService.StartFleet'


class XAmzTarget54(Enum):
    PhotonAdminProxyService_StartImageBuilder = (
        'PhotonAdminProxyService.StartImageBuilder'
    )


class XAmzTarget55(Enum):
    PhotonAdminProxyService_StopFleet = 'PhotonAdminProxyService.StopFleet'


class XAmzTarget56(Enum):
    PhotonAdminProxyService_StopImageBuilder = (
        'PhotonAdminProxyService.StopImageBuilder'
    )


class XAmzTarget57(Enum):
    PhotonAdminProxyService_TagResource = 'PhotonAdminProxyService.TagResource'


class XAmzTarget58(Enum):
    PhotonAdminProxyService_UntagResource = 'PhotonAdminProxyService.UntagResource'


class XAmzTarget59(Enum):
    PhotonAdminProxyService_UpdateApplication = (
        'PhotonAdminProxyService.UpdateApplication'
    )


class XAmzTarget60(Enum):
    PhotonAdminProxyService_UpdateDirectoryConfig = (
        'PhotonAdminProxyService.UpdateDirectoryConfig'
    )


class XAmzTarget61(Enum):
    PhotonAdminProxyService_UpdateEntitlement = (
        'PhotonAdminProxyService.UpdateEntitlement'
    )


class XAmzTarget62(Enum):
    PhotonAdminProxyService_UpdateFleet = 'PhotonAdminProxyService.UpdateFleet'


class XAmzTarget63(Enum):
    PhotonAdminProxyService_UpdateImagePermissions = (
        'PhotonAdminProxyService.UpdateImagePermissions'
    )


class XAmzTarget64(Enum):
    PhotonAdminProxyService_UpdateStack = 'PhotonAdminProxyService.UpdateStack'


class AccessEndpoint(BaseModel):
    EndpointType: AccessEndpointType
    VpceId: Optional[String] = None


class AccessEndpointList(RootModel[List[AccessEndpoint]]):
    root: List[AccessEndpoint] = Field(..., max_length=4, min_length=1)


class ApplicationFleetAssociation(BaseModel):
    ApplicationArn: Arn
    FleetName: String


class ApplicationFleetAssociationList(RootModel[List[ApplicationFleetAssociation]]):
    root: List[ApplicationFleetAssociation] = Field(..., max_length=25, min_length=1)


class ApplicationSettings(BaseModel):
    Enabled: Boolean
    SettingsGroup_1: Optional[SettingsGroup] = Field(None, alias='SettingsGroup')


class ApplicationSettingsResponse(BaseModel):
    Enabled: Optional[Boolean] = None
    S3BucketName: Optional[String] = None
    SettingsGroup_1: Optional[SettingsGroup] = Field(None, alias='SettingsGroup')


class AssociateApplicationFleetRequest(BaseModel):
    ApplicationArn: Arn
    FleetName: Name


class AssociateApplicationFleetResult(BaseModel):
    ApplicationFleetAssociation_1: Optional[ApplicationFleetAssociation] = Field(
        None, alias='ApplicationFleetAssociation'
    )


class AssociateApplicationToEntitlementRequest(BaseModel):
    ApplicationIdentifier: String
    EntitlementName: Name
    StackName: Name


class AssociateFleetRequest(BaseModel):
    FleetName: String
    StackName: String


class CertificateBasedAuthProperties(BaseModel):
    CertificateAuthorityArn: Optional[Arn] = None
    Status: Optional[CertificateBasedAuthStatus] = None


class ComputeCapacity(BaseModel):
    DesiredInstances: Integer


class ComputeCapacityStatus(BaseModel):
    Available: Optional[Integer] = None
    Desired: Integer
    InUse: Optional[Integer] = None
    Running: Optional[Integer] = None


class CopyImageRequest(BaseModel):
    DestinationImageDescription: Optional[Description] = None
    DestinationImageName: Name
    DestinationRegion: RegionName
    SourceImageName: Name


class CopyImageResponse(BaseModel):
    DestinationImageName: Optional[Name] = None


class CreateApplicationRequest(BaseModel):
    AppBlockArn: Arn
    Description_1: Optional[Description] = Field(None, alias='Description')
    DisplayName_1: Optional[DisplayName] = Field(None, alias='DisplayName')
    IconS3Location: S3Location
    InstanceFamilies: StringList
    LaunchParameters: Optional[String] = None
    LaunchPath: String
    Name_1: Name = Field(..., alias='Name')
    Platforms_1: Platforms = Field(..., alias='Platforms')
    Tags_1: Optional[Tags] = Field(None, alias='Tags')
    WorkingDirectory: Optional[String] = None


class CreateDirectoryConfigRequest(BaseModel):
    CertificateBasedAuthProperties_1: Optional[CertificateBasedAuthProperties] = Field(
        None, alias='CertificateBasedAuthProperties'
    )
    DirectoryName_1: DirectoryName = Field(..., alias='DirectoryName')
    OrganizationalUnitDistinguishedNames: OrganizationalUnitDistinguishedNamesList
    ServiceAccountCredentials_1: Optional[ServiceAccountCredentials] = Field(
        None, alias='ServiceAccountCredentials'
    )


class CreateImageBuilderStreamingURLRequest(BaseModel):
    Name: String
    Validity: Optional[Long] = None


class CreateImageBuilderStreamingURLResult(BaseModel):
    Expires: Optional[Timestamp] = None
    StreamingURL: Optional[String] = None


class CreateStreamingURLRequest(BaseModel):
    ApplicationId: Optional[String] = None
    FleetName: String
    SessionContext: Optional[String] = None
    StackName: String
    UserId: StreamingUrlUserId
    Validity: Optional[Long] = None


class CreateStreamingURLResult(BaseModel):
    Expires: Optional[Timestamp] = None
    StreamingURL: Optional[String] = None


class CreateUpdatedImageRequest(BaseModel):
    dryRun: Optional[Boolean] = None
    existingImageName: Name
    newImageDescription: Optional[Description] = None
    newImageDisplayName: Optional[DisplayName] = None
    newImageName: Name
    newImageTags: Optional[Tags] = None


class CreateUsageReportSubscriptionResult(BaseModel):
    S3BucketName: Optional[String] = None
    Schedule: Optional[UsageReportSchedule] = None


class CreateUserRequest(BaseModel):
    AuthenticationType_1: AuthenticationType = Field(..., alias='AuthenticationType')
    FirstName: Optional[UserAttributeValue] = None
    LastName: Optional[UserAttributeValue] = None
    MessageAction_1: Optional[MessageAction] = Field(None, alias='MessageAction')
    UserName: Username


class DeleteAppBlockRequest(BaseModel):
    Name_1: Name = Field(..., alias='Name')


class DeleteApplicationRequest(BaseModel):
    Name_1: Name = Field(..., alias='Name')


class DeleteDirectoryConfigRequest(BaseModel):
    DirectoryName_1: DirectoryName = Field(..., alias='DirectoryName')


class DeleteEntitlementRequest(BaseModel):
    Name_1: Name = Field(..., alias='Name')
    StackName: Name


class DeleteFleetRequest(BaseModel):
    Name: String


class DeleteImageBuilderRequest(BaseModel):
    Name_1: Name = Field(..., alias='Name')


class DeleteImagePermissionsRequest(BaseModel):
    Name_1: Name = Field(..., alias='Name')
    SharedAccountId: AwsAccountId


class DeleteImageRequest(BaseModel):
    Name_1: Name = Field(..., alias='Name')


class DeleteStackRequest(BaseModel):
    Name: String


class DeleteUserRequest(BaseModel):
    AuthenticationType_1: AuthenticationType = Field(..., alias='AuthenticationType')
    UserName: Username


class DescribeAppBlocksRequest(BaseModel):
    Arns: Optional[ArnList] = None
    MaxResults: Optional[Integer] = None
    NextToken: Optional[String] = None


class DescribeApplicationFleetAssociationsRequest(BaseModel):
    ApplicationArn: Optional[Arn] = None
    FleetName: Optional[Name] = None
    MaxResults: Optional[Integer] = None
    NextToken: Optional[String] = None


class DescribeApplicationFleetAssociationsResult(BaseModel):
    ApplicationFleetAssociations: Optional[ApplicationFleetAssociationList] = None
    NextToken: Optional[String] = None


class DescribeApplicationsRequest(BaseModel):
    Arns: Optional[ArnList] = None
    MaxResults: Optional[Integer] = None
    NextToken: Optional[String] = None


class DescribeDirectoryConfigsRequest(BaseModel):
    DirectoryNames: Optional[DirectoryNameList] = None
    MaxResults: Optional[Integer] = None
    NextToken: Optional[String] = None


class DescribeEntitlementsRequest(BaseModel):
    MaxResults: Optional[Integer] = None
    Name_1: Optional[Name] = Field(None, alias='Name')
    NextToken: Optional[String] = None
    StackName: Name


class DescribeFleetsRequest(BaseModel):
    Names: Optional[StringList] = None
    NextToken: Optional[String] = None


class DescribeImageBuildersRequest(BaseModel):
    MaxResults: Optional[Integer] = None
    Names: Optional[StringList] = None
    NextToken: Optional[String] = None


class DescribeImagePermissionsRequest(BaseModel):
    MaxResults_1: Optional[MaxResults] = Field(None, alias='MaxResults')
    Name_1: Name = Field(..., alias='Name')
    NextToken: Optional[String] = None
    SharedAwsAccountIds: Optional[AwsAccountIdList] = None


class DescribeImagePermissionsResult(BaseModel):
    Name_1: Optional[Name] = Field(None, alias='Name')
    NextToken: Optional[String] = None
    SharedImagePermissionsList_1: Optional[SharedImagePermissionsList] = Field(
        None, alias='SharedImagePermissionsList'
    )


class DescribeImagesRequest(BaseModel):
    Arns: Optional[ArnList] = None
    MaxResults: Optional[DescribeImagesMaxResults] = None
    Names: Optional[StringList] = None
    NextToken: Optional[String] = None
    Type: Optional[VisibilityType] = None


class DescribeSessionsRequest(BaseModel):
    AuthenticationType_1: Optional[AuthenticationType] = Field(
        None, alias='AuthenticationType'
    )
    FleetName: String
    Limit: Optional[Integer] = None
    NextToken: Optional[String] = None
    StackName: String
    UserId_1: Optional[UserId] = Field(None, alias='UserId')


class DescribeStacksRequest(BaseModel):
    Names: Optional[StringList] = None
    NextToken: Optional[String] = None


class DescribeUsageReportSubscriptionsRequest(BaseModel):
    MaxResults: Optional[Integer] = None
    NextToken: Optional[String] = None


class DescribeUserStackAssociationsRequest(BaseModel):
    AuthenticationType_1: Optional[AuthenticationType] = Field(
        None, alias='AuthenticationType'
    )
    MaxResults_1: Optional[MaxResults] = Field(None, alias='MaxResults')
    NextToken: Optional[String] = None
    StackName: Optional[String] = None
    UserName: Optional[Username] = None


class DescribeUsersRequest(BaseModel):
    AuthenticationType_1: AuthenticationType = Field(..., alias='AuthenticationType')
    MaxResults: Optional[Integer] = None
    NextToken: Optional[String] = None


class DirectoryConfig(BaseModel):
    CertificateBasedAuthProperties_1: Optional[CertificateBasedAuthProperties] = Field(
        None, alias='CertificateBasedAuthProperties'
    )
    CreatedTime: Optional[Timestamp] = None
    DirectoryName_1: DirectoryName = Field(..., alias='DirectoryName')
    OrganizationalUnitDistinguishedNames: Optional[
        OrganizationalUnitDistinguishedNamesList
    ] = None
    ServiceAccountCredentials_1: Optional[ServiceAccountCredentials] = Field(
        None, alias='ServiceAccountCredentials'
    )


class DirectoryConfigList(RootModel[List[DirectoryConfig]]):
    root: List[DirectoryConfig]


class DisableUserRequest(BaseModel):
    AuthenticationType_1: AuthenticationType = Field(..., alias='AuthenticationType')
    UserName: Username


class DisassociateApplicationFleetRequest(BaseModel):
    ApplicationArn: Arn
    FleetName: Name


class DisassociateApplicationFromEntitlementRequest(BaseModel):
    ApplicationIdentifier: String
    EntitlementName: Name
    StackName: Name


class DisassociateFleetRequest(BaseModel):
    FleetName: String
    StackName: String


class DomainJoinInfo(BaseModel):
    DirectoryName_1: Optional[DirectoryName] = Field(None, alias='DirectoryName')
    OrganizationalUnitDistinguishedName_1: Optional[
        OrganizationalUnitDistinguishedName
    ] = Field(None, alias='OrganizationalUnitDistinguishedName')


class EnableUserRequest(BaseModel):
    AuthenticationType_1: AuthenticationType = Field(..., alias='AuthenticationType')
    UserName: Username


class EntitledApplication(BaseModel):
    ApplicationIdentifier: String


class EntitledApplicationList(RootModel[List[EntitledApplication]]):
    root: List[EntitledApplication]


class EntitlementAttribute(BaseModel):
    Name: String
    Value: String


class EntitlementAttributeList(RootModel[List[EntitlementAttribute]]):
    root: List[EntitlementAttribute] = Field(..., min_length=1)


class ExpireSessionRequest(BaseModel):
    SessionId: String


class FleetError(BaseModel):
    ErrorCode: Optional[FleetErrorCode] = None
    ErrorMessage: Optional[String] = None


class FleetErrors(RootModel[List[FleetError]]):
    root: List[FleetError]


class ImageBuilderStateChangeReason(BaseModel):
    Code: Optional[ImageBuilderStateChangeReasonCode] = None
    Message: Optional[String] = None


class ImageStateChangeReason(BaseModel):
    Code: Optional[ImageStateChangeReasonCode] = None
    Message: Optional[String] = None


class LastReportGenerationExecutionError(BaseModel):
    ErrorCode: Optional[UsageReportExecutionErrorCode] = None
    ErrorMessage: Optional[String] = None


class LastReportGenerationExecutionErrors(
    RootModel[List[LastReportGenerationExecutionError]]
):
    root: List[LastReportGenerationExecutionError]


class ListAssociatedFleetsRequest(BaseModel):
    NextToken: Optional[String] = None
    StackName: String


class ListAssociatedFleetsResult(BaseModel):
    Names: Optional[StringList] = None
    NextToken: Optional[String] = None


class ListAssociatedStacksRequest(BaseModel):
    FleetName: String
    NextToken: Optional[String] = None


class ListAssociatedStacksResult(BaseModel):
    Names: Optional[StringList] = None
    NextToken: Optional[String] = None


class ListEntitledApplicationsRequest(BaseModel):
    EntitlementName: Name
    MaxResults: Optional[Integer] = None
    NextToken: Optional[String] = None
    StackName: Name


class ListEntitledApplicationsResult(BaseModel):
    EntitledApplications: Optional[EntitledApplicationList] = None
    NextToken: Optional[String] = None


class ListTagsForResourceResponse(BaseModel):
    Tags_1: Optional[Tags] = Field(None, alias='Tags')


class Metadata(RootModel[Optional[Dict[str, String]]]):
    root: Optional[Dict[str, String]] = None


class NetworkAccessConfiguration(BaseModel):
    EniId: Optional[String] = None
    EniPrivateIpAddress: Optional[String] = None


class ResourceError(BaseModel):
    ErrorCode: Optional[FleetErrorCode] = None
    ErrorMessage: Optional[String] = None
    ErrorTimestamp: Optional[Timestamp] = None


class ResourceErrors(RootModel[List[ResourceError]]):
    root: List[ResourceError]


class ScriptDetails(BaseModel):
    ExecutableParameters: Optional[String] = None
    ExecutablePath: String
    ScriptS3Location: S3Location
    TimeoutInSeconds: Integer


class SecurityGroupIdList(RootModel[List[String]]):
    root: List[String] = Field(
        ..., description='The security group identifiers.', max_length=5
    )


class Session(BaseModel):
    AuthenticationType_1: Optional[AuthenticationType] = Field(
        None, alias='AuthenticationType'
    )
    ConnectionState: Optional[SessionConnectionState] = None
    FleetName: String
    Id: String
    MaxExpirationTime: Optional[Timestamp] = None
    NetworkAccessConfiguration_1: Optional[NetworkAccessConfiguration] = Field(
        None, alias='NetworkAccessConfiguration'
    )
    StackName: String
    StartTime: Optional[Timestamp] = None
    State: SessionState
    UserId_1: UserId = Field(..., alias='UserId')


class SessionList(RootModel[List[Session]]):
    root: List[Session] = Field(..., description='List of sessions.')


class StackError(BaseModel):
    ErrorCode: Optional[StackErrorCode] = None
    ErrorMessage: Optional[String] = None


class StackErrors(RootModel[List[StackError]]):
    root: List[StackError] = Field(..., description='The stack errors.')


class StartFleetRequest(BaseModel):
    Name: String


class StartImageBuilderRequest(BaseModel):
    AppstreamAgentVersion_1: Optional[AppstreamAgentVersion] = Field(
        None, alias='AppstreamAgentVersion'
    )
    Name: String


class StopFleetRequest(BaseModel):
    Name: String


class StopImageBuilderRequest(BaseModel):
    Name: String


class StorageConnector(BaseModel):
    ConnectorType: StorageConnectorType
    Domains: Optional[DomainList] = None
    ResourceIdentifier_1: Optional[ResourceIdentifier] = Field(
        None, alias='ResourceIdentifier'
    )


class StorageConnectorList(RootModel[List[StorageConnector]]):
    root: List[StorageConnector] = Field(..., description='The storage connectors.')


class TagResourceRequest(BaseModel):
    ResourceArn: Arn
    Tags_1: Tags = Field(..., alias='Tags')


class UpdateDirectoryConfigRequest(BaseModel):
    CertificateBasedAuthProperties_1: Optional[CertificateBasedAuthProperties] = Field(
        None, alias='CertificateBasedAuthProperties'
    )
    DirectoryName_1: DirectoryName = Field(..., alias='DirectoryName')
    OrganizationalUnitDistinguishedNames: Optional[
        OrganizationalUnitDistinguishedNamesList
    ] = None
    ServiceAccountCredentials_1: Optional[ServiceAccountCredentials] = Field(
        None, alias='ServiceAccountCredentials'
    )


class UpdateDirectoryConfigResult(BaseModel):
    DirectoryConfig_1: Optional[DirectoryConfig] = Field(None, alias='DirectoryConfig')


class UpdateEntitlementRequest(BaseModel):
    AppVisibility_1: Optional[AppVisibility] = Field(None, alias='AppVisibility')
    Attributes: Optional[EntitlementAttributeList] = None
    Description_1: Optional[Description] = Field(None, alias='Description')
    Name_1: Name = Field(..., alias='Name')
    StackName: Name


class UpdateStackRequest(BaseModel):
    AccessEndpoints: Optional[AccessEndpointList] = None
    ApplicationSettings_1: Optional[ApplicationSettings] = Field(
        None, alias='ApplicationSettings'
    )
    AttributesToDelete: Optional[StackAttributes] = None
    DeleteStorageConnectors: Optional[Boolean] = None
    Description_1: Optional[Description] = Field(None, alias='Description')
    DisplayName_1: Optional[DisplayName] = Field(None, alias='DisplayName')
    EmbedHostDomains_1: Optional[EmbedHostDomains] = Field(
        None, alias='EmbedHostDomains'
    )
    FeedbackURL_1: Optional[FeedbackURL] = Field(None, alias='FeedbackURL')
    Name: String
    RedirectURL_1: Optional[RedirectURL] = Field(None, alias='RedirectURL')
    StorageConnectors: Optional[StorageConnectorList] = None
    StreamingExperienceSettings_1: Optional[StreamingExperienceSettings] = Field(
        None, alias='StreamingExperienceSettings'
    )
    UserSettings: Optional[UserSettingList] = None


class UsageReportSubscription(BaseModel):
    LastGeneratedReportDate: Optional[Timestamp] = None
    S3BucketName: Optional[String] = None
    Schedule: Optional[UsageReportSchedule] = None
    SubscriptionErrors: Optional[LastReportGenerationExecutionErrors] = None


class UsageReportSubscriptionList(RootModel[List[UsageReportSubscription]]):
    root: List[UsageReportSubscription]


class User(BaseModel):
    Arn_1: Optional[Arn] = Field(None, alias='Arn')
    AuthenticationType_1: AuthenticationType = Field(..., alias='AuthenticationType')
    CreatedTime: Optional[Timestamp] = None
    Enabled: Optional[Boolean] = None
    FirstName: Optional[UserAttributeValue] = None
    LastName: Optional[UserAttributeValue] = None
    Status: Optional[String] = None
    UserName: Optional[Username] = None


class UserList(RootModel[List[User]]):
    root: List[User]


class UserStackAssociation(BaseModel):
    AuthenticationType_1: AuthenticationType = Field(..., alias='AuthenticationType')
    SendEmailNotification: Optional[Boolean] = None
    StackName: String
    UserName: Username


class UserStackAssociationError(BaseModel):
    ErrorCode: Optional[UserStackAssociationErrorCode] = None
    ErrorMessage: Optional[String] = None
    UserStackAssociation_1: Optional[UserStackAssociation] = Field(
        None, alias='UserStackAssociation'
    )


class UserStackAssociationErrorList(RootModel[List[UserStackAssociationError]]):
    root: List[UserStackAssociationError]


class UserStackAssociationList(RootModel[List[UserStackAssociation]]):
    root: List[UserStackAssociation] = Field(..., max_length=25, min_length=1)


class VpcConfig(BaseModel):
    SecurityGroupIds: Optional[SecurityGroupIdList] = None
    SubnetIds: Optional[SubnetIdList] = None


class AppBlock(BaseModel):
    Arn_1: Arn = Field(..., alias='Arn')
    CreatedTime: Optional[Timestamp] = None
    Description: Optional[String] = None
    DisplayName: Optional[String] = None
    Name: String
    SetupScriptDetails: ScriptDetails
    SourceS3Location: Optional[S3Location] = None


class AppBlocks(RootModel[List[AppBlock]]):
    root: List[AppBlock]


class Application(BaseModel):
    AppBlockArn: Optional[Arn] = None
    Arn_1: Optional[Arn] = Field(None, alias='Arn')
    CreatedTime: Optional[Timestamp] = None
    Description: Optional[String] = None
    DisplayName: Optional[String] = None
    Enabled: Optional[Boolean] = None
    IconS3Location: Optional[S3Location] = None
    IconURL: Optional[String] = None
    InstanceFamilies: Optional[StringList] = None
    LaunchParameters: Optional[String] = None
    LaunchPath: Optional[String] = None
    Metadata_1: Optional[Metadata] = Field(None, alias='Metadata')
    Name: Optional[String] = None
    Platforms_1: Optional[Platforms] = Field(None, alias='Platforms')
    WorkingDirectory: Optional[String] = None


class Applications(RootModel[List[Application]]):
    root: List[Application]


class BatchAssociateUserStackRequest(BaseModel):
    UserStackAssociations: UserStackAssociationList


class BatchAssociateUserStackResult(BaseModel):
    errors: Optional[UserStackAssociationErrorList] = None


class BatchDisassociateUserStackRequest(BaseModel):
    UserStackAssociations: UserStackAssociationList


class BatchDisassociateUserStackResult(BaseModel):
    errors: Optional[UserStackAssociationErrorList] = None


class CreateAppBlockRequest(BaseModel):
    Description_1: Optional[Description] = Field(None, alias='Description')
    DisplayName_1: Optional[DisplayName] = Field(None, alias='DisplayName')
    Name_1: Name = Field(..., alias='Name')
    SetupScriptDetails: ScriptDetails
    SourceS3Location: S3Location
    Tags_1: Optional[Tags] = Field(None, alias='Tags')


class CreateAppBlockResult(BaseModel):
    AppBlock_1: Optional[AppBlock] = Field(None, alias='AppBlock')


class CreateApplicationResult(BaseModel):
    Application_1: Optional[Application] = Field(None, alias='Application')


class CreateDirectoryConfigResult(BaseModel):
    DirectoryConfig_1: Optional[DirectoryConfig] = Field(None, alias='DirectoryConfig')


class CreateEntitlementRequest(BaseModel):
    AppVisibility_1: AppVisibility = Field(..., alias='AppVisibility')
    Attributes: EntitlementAttributeList
    Description_1: Optional[Description] = Field(None, alias='Description')
    Name_1: Name = Field(..., alias='Name')
    StackName: Name


class CreateFleetRequest(BaseModel):
    ComputeCapacity_1: Optional[ComputeCapacity] = Field(None, alias='ComputeCapacity')
    Description_1: Optional[Description] = Field(None, alias='Description')
    DisconnectTimeoutInSeconds: Optional[Integer] = None
    DisplayName_1: Optional[DisplayName] = Field(None, alias='DisplayName')
    DomainJoinInfo_1: Optional[DomainJoinInfo] = Field(None, alias='DomainJoinInfo')
    EnableDefaultInternetAccess: Optional[BooleanObject] = None
    FleetType_1: Optional[FleetType] = Field(None, alias='FleetType')
    IamRoleArn: Optional[Arn] = None
    IdleDisconnectTimeoutInSeconds: Optional[Integer] = None
    ImageArn: Optional[Arn] = None
    ImageName: Optional[String] = None
    InstanceType: String
    MaxConcurrentSessions: Optional[Integer] = None
    MaxUserDurationInSeconds: Optional[Integer] = None
    Name_1: Name = Field(..., alias='Name')
    Platform: Optional[PlatformType] = None
    SessionScriptS3Location: Optional[S3Location] = None
    StreamView_1: Optional[StreamView] = Field(None, alias='StreamView')
    Tags_1: Optional[Tags] = Field(None, alias='Tags')
    UsbDeviceFilterStrings_1: Optional[UsbDeviceFilterStrings] = Field(
        None, alias='UsbDeviceFilterStrings'
    )
    VpcConfig_1: Optional[VpcConfig] = Field(None, alias='VpcConfig')


class CreateImageBuilderRequest(BaseModel):
    AccessEndpoints: Optional[AccessEndpointList] = None
    AppstreamAgentVersion_1: Optional[AppstreamAgentVersion] = Field(
        None, alias='AppstreamAgentVersion'
    )
    Description_1: Optional[Description] = Field(None, alias='Description')
    DisplayName_1: Optional[DisplayName] = Field(None, alias='DisplayName')
    DomainJoinInfo_1: Optional[DomainJoinInfo] = Field(None, alias='DomainJoinInfo')
    EnableDefaultInternetAccess: Optional[BooleanObject] = None
    IamRoleArn: Optional[Arn] = None
    ImageArn: Optional[Arn] = None
    ImageName: Optional[String] = None
    InstanceType: String
    Name_1: Name = Field(..., alias='Name')
    Tags_1: Optional[Tags] = Field(None, alias='Tags')
    VpcConfig_1: Optional[VpcConfig] = Field(None, alias='VpcConfig')


class CreateStackRequest(BaseModel):
    AccessEndpoints: Optional[AccessEndpointList] = None
    ApplicationSettings_1: Optional[ApplicationSettings] = Field(
        None, alias='ApplicationSettings'
    )
    Description_1: Optional[Description] = Field(None, alias='Description')
    DisplayName_1: Optional[DisplayName] = Field(None, alias='DisplayName')
    EmbedHostDomains_1: Optional[EmbedHostDomains] = Field(
        None, alias='EmbedHostDomains'
    )
    FeedbackURL_1: Optional[FeedbackURL] = Field(None, alias='FeedbackURL')
    Name_1: Name = Field(..., alias='Name')
    RedirectURL_1: Optional[RedirectURL] = Field(None, alias='RedirectURL')
    StorageConnectors: Optional[StorageConnectorList] = None
    StreamingExperienceSettings_1: Optional[StreamingExperienceSettings] = Field(
        None, alias='StreamingExperienceSettings'
    )
    Tags_1: Optional[Tags] = Field(None, alias='Tags')
    UserSettings: Optional[UserSettingList] = None


class DescribeAppBlocksResult(BaseModel):
    AppBlocks_1: Optional[AppBlocks] = Field(None, alias='AppBlocks')
    NextToken: Optional[String] = None


class DescribeApplicationsResult(BaseModel):
    Applications_1: Optional[Applications] = Field(None, alias='Applications')
    NextToken: Optional[String] = None


class DescribeDirectoryConfigsResult(BaseModel):
    DirectoryConfigs: Optional[DirectoryConfigList] = None
    NextToken: Optional[String] = None


class DescribeSessionsResult(BaseModel):
    NextToken: Optional[String] = None
    Sessions: Optional[SessionList] = None


class DescribeUsageReportSubscriptionsResult(BaseModel):
    NextToken: Optional[String] = None
    UsageReportSubscriptions: Optional[UsageReportSubscriptionList] = None


class DescribeUserStackAssociationsResult(BaseModel):
    NextToken: Optional[String] = None
    UserStackAssociations: Optional[UserStackAssociationList] = None


class DescribeUsersResult(BaseModel):
    NextToken: Optional[String] = None
    Users: Optional[UserList] = None


class Entitlement(BaseModel):
    AppVisibility_1: AppVisibility = Field(..., alias='AppVisibility')
    Attributes: EntitlementAttributeList
    CreatedTime: Optional[Timestamp] = None
    Description_1: Optional[Description] = Field(None, alias='Description')
    LastModifiedTime: Optional[Timestamp] = None
    Name_1: Name = Field(..., alias='Name')
    StackName: Name


class EntitlementList(RootModel[List[Entitlement]]):
    root: List[Entitlement]


class Fleet(BaseModel):
    Arn_1: Arn = Field(..., alias='Arn')
    ComputeCapacityStatus_1: ComputeCapacityStatus = Field(
        ..., alias='ComputeCapacityStatus'
    )
    CreatedTime: Optional[Timestamp] = None
    Description: Optional[String] = None
    DisconnectTimeoutInSeconds: Optional[Integer] = None
    DisplayName: Optional[String] = None
    DomainJoinInfo_1: Optional[DomainJoinInfo] = Field(None, alias='DomainJoinInfo')
    EnableDefaultInternetAccess: Optional[BooleanObject] = None
    FleetErrors_1: Optional[FleetErrors] = Field(None, alias='FleetErrors')
    FleetType_1: Optional[FleetType] = Field(None, alias='FleetType')
    IamRoleArn: Optional[Arn] = None
    IdleDisconnectTimeoutInSeconds: Optional[Integer] = None
    ImageArn: Optional[Arn] = None
    ImageName: Optional[String] = None
    InstanceType: String
    MaxConcurrentSessions: Optional[Integer] = None
    MaxUserDurationInSeconds: Optional[Integer] = None
    Name: String
    Platform: Optional[PlatformType] = None
    SessionScriptS3Location: Optional[S3Location] = None
    State: FleetState
    StreamView_1: Optional[StreamView] = Field(None, alias='StreamView')
    UsbDeviceFilterStrings_1: Optional[UsbDeviceFilterStrings] = Field(
        None, alias='UsbDeviceFilterStrings'
    )
    VpcConfig_1: Optional[VpcConfig] = Field(None, alias='VpcConfig')


class FleetList(RootModel[List[Fleet]]):
    root: List[Fleet] = Field(..., description='The fleets.')


class Image(BaseModel):
    Applications_1: Optional[Applications] = Field(None, alias='Applications')
    AppstreamAgentVersion_1: Optional[AppstreamAgentVersion] = Field(
        None, alias='AppstreamAgentVersion'
    )
    Arn_1: Optional[Arn] = Field(None, alias='Arn')
    BaseImageArn: Optional[Arn] = None
    CreatedTime: Optional[Timestamp] = None
    Description: Optional[String] = None
    DisplayName: Optional[String] = None
    ImageBuilderName: Optional[String] = None
    ImageBuilderSupported: Optional[Boolean] = None
    ImageErrors: Optional[ResourceErrors] = None
    ImagePermissions_1: Optional[ImagePermissions] = Field(
        None, alias='ImagePermissions'
    )
    Name: String
    Platform: Optional[PlatformType] = None
    PublicBaseImageReleasedDate: Optional[Timestamp] = None
    State: Optional[ImageState] = None
    StateChangeReason: Optional[ImageStateChangeReason] = None
    Visibility: Optional[VisibilityType] = None


class ImageBuilder(BaseModel):
    AccessEndpoints: Optional[AccessEndpointList] = None
    AppstreamAgentVersion_1: Optional[AppstreamAgentVersion] = Field(
        None, alias='AppstreamAgentVersion'
    )
    Arn_1: Optional[Arn] = Field(None, alias='Arn')
    CreatedTime: Optional[Timestamp] = None
    Description: Optional[String] = None
    DisplayName: Optional[String] = None
    DomainJoinInfo_1: Optional[DomainJoinInfo] = Field(None, alias='DomainJoinInfo')
    EnableDefaultInternetAccess: Optional[BooleanObject] = None
    IamRoleArn: Optional[Arn] = None
    ImageArn: Optional[Arn] = None
    ImageBuilderErrors: Optional[ResourceErrors] = None
    InstanceType: Optional[String] = None
    Name: String
    NetworkAccessConfiguration_1: Optional[NetworkAccessConfiguration] = Field(
        None, alias='NetworkAccessConfiguration'
    )
    Platform: Optional[PlatformType] = None
    State: Optional[ImageBuilderState] = None
    StateChangeReason: Optional[ImageBuilderStateChangeReason] = None
    VpcConfig_1: Optional[VpcConfig] = Field(None, alias='VpcConfig')


class ImageBuilderList(RootModel[List[ImageBuilder]]):
    root: List[ImageBuilder]


class ImageList(RootModel[List[Image]]):
    root: List[Image]


class Stack(BaseModel):
    AccessEndpoints: Optional[AccessEndpointList] = None
    ApplicationSettings: Optional[ApplicationSettingsResponse] = None
    Arn_1: Optional[Arn] = Field(None, alias='Arn')
    CreatedTime: Optional[Timestamp] = None
    Description: Optional[String] = None
    DisplayName: Optional[String] = None
    EmbedHostDomains_1: Optional[EmbedHostDomains] = Field(
        None, alias='EmbedHostDomains'
    )
    FeedbackURL_1: Optional[FeedbackURL] = Field(None, alias='FeedbackURL')
    Name: String
    RedirectURL_1: Optional[RedirectURL] = Field(None, alias='RedirectURL')
    StackErrors_1: Optional[StackErrors] = Field(None, alias='StackErrors')
    StorageConnectors: Optional[StorageConnectorList] = None
    StreamingExperienceSettings_1: Optional[StreamingExperienceSettings] = Field(
        None, alias='StreamingExperienceSettings'
    )
    UserSettings: Optional[UserSettingList] = None


class StackList(RootModel[List[Stack]]):
    root: List[Stack] = Field(..., description='The stacks.')


class StartImageBuilderResult(BaseModel):
    ImageBuilder_1: Optional[ImageBuilder] = Field(None, alias='ImageBuilder')


class StopImageBuilderResult(BaseModel):
    ImageBuilder_1: Optional[ImageBuilder] = Field(None, alias='ImageBuilder')


class UpdateApplicationResult(BaseModel):
    Application_1: Optional[Application] = Field(None, alias='Application')


class UpdateEntitlementResult(BaseModel):
    Entitlement_1: Optional[Entitlement] = Field(None, alias='Entitlement')


class UpdateFleetRequest(BaseModel):
    AttributesToDelete: Optional[FleetAttributes] = None
    ComputeCapacity_1: Optional[ComputeCapacity] = Field(None, alias='ComputeCapacity')
    DeleteVpcConfig: Optional[Boolean] = None
    Description_1: Optional[Description] = Field(None, alias='Description')
    DisconnectTimeoutInSeconds: Optional[Integer] = None
    DisplayName_1: Optional[DisplayName] = Field(None, alias='DisplayName')
    DomainJoinInfo_1: Optional[DomainJoinInfo] = Field(None, alias='DomainJoinInfo')
    EnableDefaultInternetAccess: Optional[BooleanObject] = None
    IamRoleArn: Optional[Arn] = None
    IdleDisconnectTimeoutInSeconds: Optional[Integer] = None
    ImageArn: Optional[Arn] = None
    ImageName: Optional[String] = None
    InstanceType: Optional[String] = None
    MaxConcurrentSessions: Optional[Integer] = None
    MaxUserDurationInSeconds: Optional[Integer] = None
    Name: Optional[String] = None
    Platform: Optional[PlatformType] = None
    SessionScriptS3Location: Optional[S3Location] = None
    StreamView_1: Optional[StreamView] = Field(None, alias='StreamView')
    UsbDeviceFilterStrings_1: Optional[UsbDeviceFilterStrings] = Field(
        None, alias='UsbDeviceFilterStrings'
    )
    VpcConfig_1: Optional[VpcConfig] = Field(None, alias='VpcConfig')


class UpdateFleetResult(BaseModel):
    Fleet_1: Optional[Fleet] = Field(None, alias='Fleet')


class UpdateStackResult(BaseModel):
    Stack_1: Optional[Stack] = Field(None, alias='Stack')


class CreateEntitlementResult(BaseModel):
    Entitlement_1: Optional[Entitlement] = Field(None, alias='Entitlement')


class CreateFleetResult(BaseModel):
    Fleet_1: Optional[Fleet] = Field(None, alias='Fleet')


class CreateImageBuilderResult(BaseModel):
    ImageBuilder_1: Optional[ImageBuilder] = Field(None, alias='ImageBuilder')


class CreateStackResult(BaseModel):
    Stack_1: Optional[Stack] = Field(None, alias='Stack')


class CreateUpdatedImageResult(BaseModel):
    canUpdateImage: Optional[Boolean] = None
    image: Optional[Image] = None


class DeleteImageBuilderResult(BaseModel):
    ImageBuilder_1: Optional[ImageBuilder] = Field(None, alias='ImageBuilder')


class DeleteImageResult(BaseModel):
    Image_1: Optional[Image] = Field(None, alias='Image')


class DescribeEntitlementsResult(BaseModel):
    Entitlements: Optional[EntitlementList] = None
    NextToken: Optional[String] = None


class DescribeFleetsResult(BaseModel):
    Fleets: Optional[FleetList] = None
    NextToken: Optional[String] = None


class DescribeImageBuildersResult(BaseModel):
    ImageBuilders: Optional[ImageBuilderList] = None
    NextToken: Optional[String] = None


class DescribeImagesResult(BaseModel):
    Images: Optional[ImageList] = None
    NextToken: Optional[String] = None


class DescribeStacksResult(BaseModel):
    NextToken: Optional[String] = None
    Stacks: Optional[StackList] = None
